# Generated by Django 4.2.9 on 2024-01-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='password',
            field=models.CharField(default='123', max_length=50),
        ),
    ]
