# Generated by Django 4.2.9 on 2024-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_folder_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
