# Generated by Django 4.2.9 on 2024-01-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_folder_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='password',
        ),
        migrations.AlterField(
            model_name='files',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
